[package]
name = "app-core"
version = "0.1.0"
edition = "2021"

[dependencies]
salt = { path = "../.." }
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["console"] }

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = []
